### PR TITLE
feat: updating to use cert-manager and external-secrets

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Skarlso** [comment]
I'll create a link to this documentation once it's merged: https://github.com/open-component-model/MPAS/pull/120

**Comment by Skarlso** [comment]
Closes https://github.com/open-component-model/MPAS/issues/117

**Review by morri-son — CHANGES_REQUESTED** [review]
looks ok, but misses a CRD. On make run I get:

```❯ Bootstrap completed successfully!
DEMO SETUP => creating cluster external secrets
clusterrole.rbac.authorization.k8s.io/secret-reader-writer created
clusterrolebinding.rbac.authorization.k8s.io/secret-reader-writer-binding created
error: resource mapping not found for name: "secret-store-name" namespace: "" from "./manifests/external-secrets/cluster_secret_store.yaml": no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1beta1"
ensure CRDs are installed first
make: *** [Makefile:4: run] Error 1```

**Comment by Skarlso** [comment]
Are you sure you are using th latest mpas cli version?

**Comment by morri-son** [comment]
@Skarlso: Si, señor :-)

```❯ which mpas
/opt/homebrew/bin/mpas
❯ brew upgrade open-component-model/tap/mpas
Warning: open-component-model/tap/mpas 0.5.2 already installed```

**Comment by Skarlso** [comment]
Humpf. It's working for me sadly. 

What's above that error? 

```
DEMO SETUP => deploying mpas controllers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   133  100    55   1563    646 --:--:-- --:--:-- --:--:--  2379
Running mpas bootstrap ...
 ✓   Preparing Management repository mpas-ocm-applications
 ✓   Fetching bootstrap component from ghcr.io/open-component-model/mpas-bootstrap-component
 ✓   Installing flux with version v2.1.0
 ✓   Installing cert-manager with version v1.13.1
 ✓   Reconciling infrastructure components
 ✓   Waiting for cert-manager to be available
 ✓   Generating external-secrets-operator manifest with version v0.9.6
 ✓   Generating git-controller manifest with version v0.9.0
 ✓   Generating mpas-product-controller manifest with version v0.6.0
 ✓   Generating mpas-project-controller manifest with version v0.5.0
 ✓   Generating ocm-controller manifest with version v0.14.1
 ✓   Generating replication-controller manifest with version v0.8.0
 ✓   Generate certificate manifests
 ✓   Reconciling infrastructure components
 ✓   Waiting for components to be ready

Bootstrap completed successfully!
DEMO SETUP => creating cluster external secrets
clusterrole.rbac.authorization.k8s.io/secret-reader-writer created
clusterrolebinding.rbac.authorization.k8s.io/secret-reader-writer-binding created
clustersecretstore.external-secrets.io/secret-store-name created
clusterexternalsecret.external-secrets.io/pull-creds created
clusterexternalsecret.external-secrets.io/gitea-registry-credentials created
clusterexternalsecret.external-secrets.io/ocm-signing created
clusterexternalsecret.external-secrets.io/ocm-dev-ca created
DEMO SETUP => deploy tekton

```

This is how it looks like for me.

**Comment by morri-son** [comment]
```
Forwarding from 127.0.0.1:2222 -> 2222
Forwarding from [::1]:2222 -> 2222
DEMO SETUP => deploying mpas controllers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   133  100    55   1864    770 --:--:-- --:--:-- --:--:--  3032
Running mpas bootstrap ...
 ✓   Preparing Management repository mpas-ocm-applications
 ✓   Fetching bootstrap component from ghcr.io/open-component-model/mpas-bootstrap-component
 ✓   Installing flux with version v2.1.0
 ✓   Installing cert-manager with version v1.13.1
 ✓   Reconciling infrastructure components
 ✓   Waiting for cert-manager to be available
 ✓   Generating git-controller manifest with version v0.9.0
 ✓   Generating mpas-product-controller manifest with version v0.6.0
 ✓   Generating mpas-project-controller manifest with version v0.5.0
 ✓   Generating ocm-controller manifest with version v0.14.1
 ✓   Generating replication-controller manifest with version v0.8.0
 ✓   Generate certificate manifests
 ✓   Reconciling infrastructure components
 ✓   Waiting for components to be ready

Bootstrap completed successfully!
DEMO SETUP => creating cluster external secrets
clusterrole.rbac.authorization.k8s.io/secret-reader-writer created
clusterrolebinding.rbac.authorization.k8s.io/secret-reader-writer-binding created
error: resource mapping not found for name: "secret-store-name" namespace: "" from "./manifests/external-secrets/cluster_secret_store.yaml": no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1beta1"
ensure CRDs are installed first
make: *** [Makefile:4: run] Error 1
```

**Comment by Skarlso** [comment]
Yah, that's definitely not the right version 🤔

**Comment by morri-son** [comment]
@Skarlso , I used brew to install the client.

**Comment by Skarlso** [comment]
I suspect you have an mpas binary under /usr/local/bin/mpas and that takes precedence over the one brew is using?

**Comment by morri-son** [comment]
nope, as you can see in my 

```
❯ which mpas
/opt/homebrew/bin/mpas
```

:-)

**Comment by Skarlso** [comment]
hm. So do you have `/usr/local/bin/mpas`?

**Comment by morri-son** [comment]
no, as otherwise the which would show it as it follows the PATH. The latter in my case is:

```
PATH=/Users/xxxx/google-cloud-sdk/bin:/opt/homebrew/opt/findutils/libexec/gnubin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/opt/gawk/libexec/gnubin:/opt/homebrew/opt/gsed/libexec/gnubin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/ed/libexec/gnubin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/usr/local/opt/mysql-client/bin:/Users/xxxx/.krew/bin:/Users/xxxx/go/packages/bin:/Users/xxxx/go/go/bin:/Users/xxxx/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Privileges.app/Contents/Resources:/usr/local/go/bin:/Users/xxxx/.krew/bin:/Users/xxxx/.bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
```

**Comment by Skarlso** [comment]
Okay, so I guess the homebrew thing doesn't install the latest version even though it's telling you it does.

**Comment by Skarlso** [comment]
>no, as otherwise the which would show it as it follows the PATH. The latter in my case is:

That's not always true, if brew overwrote it.

**Comment by Skarlso** [comment]
You could still have the binary there and if the script is running in it's own shell, then it would execute whatever is in the basic PATH that brew didn't overwrite.

**Comment by Skarlso** [comment]
This is easy to test. I'll release a new version of MPAS. Try installing it via brew. It should have a new command called `version`. Run that. :)

**Comment by Skarlso** [comment]
@morri-son not sure how the homebrew stuff works, but I updated MPAS. If you run install now it should have a `version` component.

**Comment by Skarlso** [comment]
```
brew install open-component-model/tap/mpas
==> Tapping open-component-model/tap
Cloning into '/usr/local/Homebrew/Library/Taps/open-component-model/homebrew-tap'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 109 (delta 47), reused 15 (delta 3), pack-reused 0
Receiving objects: 100% (109/109), 29.21 KiB | 347.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Tapped 2 formulae (21 files, 79.5KB).
==> Fetching open-component-model/tap/mpas
==> Downloading https://github.com/open-component-model/MPAS/releases/download/v0.5.3/mpas_0.5.3_darwin_amd64.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/613828911/35041cd3-15ec-443e-a32c-72455
################################################################################################################################## 100.0%
==> Installing mpas from open-component-model/tap
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/mpas/0.5.3: 6 files, 85.5MB, built in 4 seconds
==> Running `brew cleanup mpas`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  MPAS git:(main) mpas version
error: unknown command "version" for "mpas"
➜  MPAS git:(main)

```

It isn't working. I'll look into it.

**Comment by Skarlso** [comment]
ah, I had a hiccup, it IS working:

```
ls -l /usr/local/bin/mpas
lrwxr-xr-x@ 1 skarlso  admin  29 Oct 30 16:18 /usr/local/bin/mpas -> ../Cellar/mpas/0.5.3/bin/mpas
➜  MPAS git:(main) mpas version
0.0.0-dev.0

```

**Comment by morri-son** [comment]
I uninstalled maps using brew and tried to get the latest version like shown in your comment above: no chance. When I execute brew install I always get the 0.5.2:

```
❯ brew install open-component-model/tap/mpas
==> Fetching open-component-model/tap/mpas
==> Downloading https://github.com/open-component-model/MPAS/releases/download/v0.5.2/mpas_0.5.2_darwin_arm64.tar.gz
Already downloaded: /Users/D032990/Library/Caches/Homebrew/downloads/5cb5d906ce9eaf6a5e084a19abe2e5f9cc1f205696273ccc3415e32ceec37f52--mpas_0.5.2_darwin_arm64.tar.gz
==> Installing mpas from open-component-model/tap
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O=#    #
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/mpas/0.5.2: 6 files, 85.0MB, built in 3 seconds
==> Running `brew cleanup mpas`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by souleb** [comment]
I think this has to do with your local brew cache. Can you try `brew upgrade`? I would also make sure that the formula is not pinned.

**Comment by morri-son** [comment]
@souleb, nothing cached, nothing pinned:

```
❯ brew unpin open-component-model/tap/mpas
Warning: mpas not pinned
❯ brew upgrade open-component-model/tap/mpas
Warning: open-component-model/tap/mpas 0.5.2 already installed
```

**Comment by morri-son** [comment]
I now downloaded the client via curl and deinstalled the one from brew. At least I was able to test the scenario for this PR successfully :)

**Review by morri-son — APPROVED** [review]
works

**Pull request merged**
